# Generated by Django 5.2.4 on 2025-10-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='رقم الموظف'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'الإدارة'), ('center', 'المركز')], default='center', max_length=20, verbose_name='الدور'),
        ),
    ]
