# Generated by Django 5.2.4 on 2025-10-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_employeeprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='police_center',
            field=models.CharField(blank=True, max_length=100, verbose_name='مركز الشرطة'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='report_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='رقم البلاغ'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='report_year',
            field=models.CharField(blank=True, max_length=4, verbose_name='سنة البلاغ'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('status', 'استعلام عن حالة طلب'), ('report_status', 'استعلام عن حالة بلاغ'), ('general', 'استعلام عام'), ('complaint', 'شكوى'), ('suggestion', 'اقتراح')], max_length=20, verbose_name='نوع الاستعلام'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(blank=True, verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
    ]
