# Generated by Django 5.2.4 on 2025-10-05 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_inquiry_police_center_inquiry_report_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('view', 'عرض بيانات'), ('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('export', 'تصدير'), ('failed_login', 'محاولة دخول فاشلة')], max_length=20, verbose_name='الإجراء')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='اسم النموذج')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='services_au_timesta_1c6593_idx'), models.Index(fields=['user', '-timestamp'], name='services_au_user_id_209cef_idx'), models.Index(fields=['action', '-timestamp'], name='services_au_action_2c276d_idx')],
            },
        ),
    ]
