# Generated by Django 5.2.4 on 2025-10-07 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_inquiry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحجز'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='محجوز بواسطة'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='رد بواسطة'),
        ),
    ]
