# Generated by Django 5.2.4 on 2025-10-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_criminalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalreport',
            name='additional_questions',
            field=models.TextField(blank=True, verbose_name='أسئلة إضافية للمتعامل'),
        ),
        migrations.AddField(
            model_name='criminalreport',
            name='client_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات للمتعامل'),
        ),
        migrations.AlterField(
            model_name='criminalreport',
            name='staff_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الموظف (داخلية)'),
        ),
        migrations.AlterField(
            model_name='criminalreport',
            name='status',
            field=models.CharField(choices=[('new_request', 'طلب جديد'), ('in_progress', 'قيد الإجراء'), ('awaiting_response', 'بانتظار الرد'), ('report_created', 'تم إنشاء بلاغ'), ('archived', 'محفوظ'), ('rejected', 'مرفوض'), ('out_of_jurisdiction', 'خارج الاختصاص')], default='new_request', max_length=30, verbose_name='الحالة'),
        ),
    ]
