# Generated by Django 5.2.4 on 2025-10-18 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_criminalreport_additional_questions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalReportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'تم إنشاء البلاغ'), ('reserved', 'تم حجز الطلب'), ('released', 'تم فك الحجز'), ('status_changed', 'تم تغيير الحالة'), ('note_added', 'تم إضافة ملاحظة'), ('question_sent', 'تم إرسال أسئلة'), ('assigned', 'تم التحويل')], max_length=20, verbose_name='نوع الإجراء')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('old_value', models.TextField(blank=True, verbose_name='القيمة القديمة')),
                ('new_value', models.TextField(blank=True, verbose_name='القيمة الجديدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='services.criminalreport', verbose_name='البلاغ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'إجراء',
                'verbose_name_plural': 'سجل الإجراءات',
                'ordering': ['-created_at'],
            },
        ),
    ]
