"""
Django settings for gov_services project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
import os
from dotenv import load_dotenv

# تحميل متغيرات البيئة من ملف .env إذا كان موجوداً
env_path = BASE_DIR / '.env'
if env_path.exists():
    load_dotenv(env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# في الإنتاج، استخدم متغيرات البيئة بدلاً من هذا
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'oai(by$3xw6h+!58r6*%9whw!*d+xuy-^6siw9vr)%@v^aop^@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# ALLOWED_HOSTS - للإنتاج والتطوير
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'services',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # للملفات الثابتة في الإنتاج
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom Security Middleware
    'services.middleware.SecurityHeadersMiddleware',
    'services.middleware.RequestLoggingMiddleware',
    'services.middleware.BlockSuspiciousIPMiddleware',
]

ROOT_URLCONF = 'gov_services.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gov_services.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Asia/Dubai'

USE_I18N = True

USE_TZ = True

# تنسيق التاريخ والوقت - نظام 12 ساعة
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y - g:i A'  # 12-hour format with AM/PM
TIME_FORMAT = 'g:i A'  # 12-hour format with AM/PM
SHORT_DATE_FORMAT = 'd/m/Y'
SHORT_DATETIME_FORMAT = 'd/m/Y - g:i A'

# استخدام التنسيق المخصص
USE_L10N = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "services" / "static",
]

# WhiteNoise settings للملفات الثابتة في الإنتاج
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========== Cache Configuration (لـ Rate Limiting) ==========
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# ========== إعدادات الأمان ==========

# Session Security - إعدادات متساهلة
SESSION_COOKIE_AGE = 31536000  # 1 سنة
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_DOMAIN = None

# CSRF Protection - إعدادات مرنة جداً لضمان عمل الموقع
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_AGE = None  # استمر للأبد
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_DOMAIN = None
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

# النطاقات الموثوقة - محلي فقط
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost',
    'http://127.0.0.1',
]

# XSS Protection
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# إعدادات إضافية للإنتاج (فعّلها عند استخدام HTTPS)
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# Password Hashing (استخدام PBKDF2 - آمن وسريع)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    # لتثبيت Argon2 (أقوى أماناً): pip install django[argon2]
    # 'django.contrib.auth.hashers.Argon2PasswordHasher',
]

# Logging للأحداث الأمنية
# Local development only - no production environment checks

# Configure logging handlers for local development
if False:  # Disabled production logging
    # Production: Use console logging only
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose'
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'django.security': {
                'handlers': ['console'],
                'level': 'WARNING',
                'propagate': False,
            },
            'services': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'security': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'requests': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }
else:
    # Development: Use both console and file logging
    import os
    log_dir = BASE_DIR / 'logs'
    
    # إنشاء مجلد logs إذا لم يكن موجوداً (للتطوير المحلي فقط)
    try:
        if not log_dir.exists():
            log_dir.mkdir(parents=True, exist_ok=True)
        
        # التحقق من إمكانية الكتابة
        test_file = log_dir / '.test'
        test_file.touch()
        test_file.unlink()
        can_write_logs = True
    except (OSError, PermissionError):
        can_write_logs = False
    
    if can_write_logs:
        # Development with file logging
        LOGGING = {
            'version': 1,
            'disable_existing_loggers': False,
            'formatters': {
                'verbose': {
                    'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                    'style': '{',
                },
                'simple': {
                    'format': '{levelname} {message}',
                    'style': '{',
                },
            },
            'handlers': {
                'console': {
                    'level': 'INFO',
                    'class': 'logging.StreamHandler',
                    'formatter': 'simple'
                },
                'file': {
                    'level': 'WARNING',
                    'class': 'logging.FileHandler',
                    'filename': BASE_DIR / 'logs' / 'django.log',
                    'formatter': 'verbose',
                },
                'security_file': {
                    'level': 'WARNING',
                    'class': 'logging.FileHandler',
                    'filename': BASE_DIR / 'logs' / 'security.log',
                    'formatter': 'verbose',
                },
            },
            'loggers': {
                'django': {
                    'handlers': ['console', 'file'],
                    'level': 'INFO',
                    'propagate': False,
                },
                'django.security': {
                    'handlers': ['security_file'],
                    'level': 'WARNING',
                    'propagate': False,
                },
                'services': {
                    'handlers': ['console', 'file'],
                    'level': 'INFO',
                    'propagate': False,
                },
                'security': {
                    'handlers': ['console', 'security_file'],
                    'level': 'INFO',
                    'propagate': False,
                },
                'requests': {
                    'handlers': ['console', 'file'],
                    'level': 'INFO',
                    'propagate': False,
                },
            },
        }
    else:
        # Fallback to console only if can't write files
        LOGGING = {
            'version': 1,
            'disable_existing_loggers': False,
            'formatters': {
                'simple': {
                    'format': '{levelname} {message}',
                    'style': '{',
                },
            },
            'handlers': {
                'console': {
                    'level': 'INFO',
                    'class': 'logging.StreamHandler',
                    'formatter': 'simple'
                },
            },
            'loggers': {
                'django': {
                    'handlers': ['console'],
                    'level': 'INFO',
                    'propagate': False,
                },
                'django.security': {
                    'handlers': ['console'],
                    'level': 'WARNING',
                    'propagate': False,
                },
                'services': {
                    'handlers': ['console'],
                    'level': 'INFO',
                    'propagate': False,
                },
                'security': {
                    'handlers': ['console'],
                    'level': 'INFO',
                    'propagate': False,
                },
                'requests': {
                    'handlers': ['console'],
                    'level': 'INFO',
                    'propagate': False,
                },
            },
        }

# ========== Email Configuration ==========
# إعدادات البريد الإلكتروني (Outlook/Microsoft 365)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = 10  # 10 seconds timeout to prevent hanging
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', 'noreply@police.ae')

# تفعيل البريد الإلكتروني في الإنتاج فقط
# في التطوير المحلي: إذا لم تكن الإعدادات موجودة، استخدم Console
if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    if 'DATABASE_URL' not in os.environ:  # محلي فقط
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    # في الإنتاج: سيتم استخدام SMTP الحقيقي من متغيرات البيئة

# ========== ملاحظة: تم إزالة إعدادات الإنتاج ==========
# المشروع الآن محلي بالكامل (Local Development Only)
