name: police-portal
region: fra
services:
- name: web
  github:
    repo: hamad26650/police-ae
    branch: main
    deploy_on_push: true
  source_dir: /gov_services
  
  # Build settings
  build_command: |
    pip install --upgrade pip
    pip install -r requirements.txt
    python manage.py collectstatic --noinput --clear
    python manage.py migrate --noinput
    python fix_database.py || echo "Setup failed but continuing"
    python auto_check_on_deploy.py || echo "Email check completed"
  
  # Run command
  run_command: gunicorn --worker-tmp-dir /dev/shm --workers 2 --bind 0.0.0.0:8080 gov_services.wsgi:application
  
  # Environment
  environment_slug: python
  
  # Instance size
  instance_size_slug: basic-xxs
  instance_count: 1
  
  # HTTP settings
  http_port: 8080
  
  # Health check
  health_check:
    http_path: /
  
  # Environment variables
  envs:
  - key: DJANGO_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DJANGO_DEBUG
    value: "False"
    scope: RUN_AND_BUILD_TIME
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: EMAIL_HOST_USER
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: EMAIL_HOST_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ALLOWED_HOSTS
    value: ".ondigitalocean.app"
    scope: RUN_TIME
  - key: CSRF_TRUSTED_ORIGINS
    value: "https://*.ondigitalocean.app"
    scope: RUN_TIME
  
  # Routes
  routes:
  - path: /
  - path: /static

databases:
- name: police-db
  engine: PG
  production: true
  version: "16"
