name: gov-services-portal
region: nyc

# Database
databases:
  - name: gov-services-db
    engine: PG
    production: true
    version: "12"

# Django App
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: hamad26650/gov-services-portal
    
    # Build Configuration
    build_command: cd gov_services && pip install -r requirements.txt && python manage.py collectstatic --noinput
    
    # Run Configuration
    run_command: cd gov_services && gunicorn gov_services.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --log-file -
    
    # Health Check
    health_check:
      http_path: /
    
    # Environment Variables (you'll add these in DigitalOcean dashboard)
    envs:
      - key: DJANGO_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      
      - key: DJANGO_DEBUG
        value: "False"
        scope: RUN_TIME
      
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      
      - key: EMAIL_HOST_USER
        scope: RUN_TIME
        type: SECRET
      
      - key: EMAIL_HOST_PASSWORD
        scope: RUN_TIME
        type: SECRET
    
    # Resources
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month
    
    # HTTP Configuration
    http_port: 8080
    
    routes:
      - path: /

