# Generated by Django 5.2.4 on 2025-09-21 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المركز')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='رمز المركز')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مركز',
                'verbose_name_plural': 'المراكز',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('prosecution', 'النيابة العامة'), ('digital_id', 'الهوية الرقمية'), ('interior', 'وزارة الداخلية'), ('sharjah_police', 'شرطة الشارقة'), ('sharjah_municipality', 'بلدية الشارقة')], max_length=100, unique=True, verbose_name='اسم الخدمة')),
                ('slug', models.SlugField(default='default-slug', max_length=100, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(verbose_name='وصف الخدمة')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='المتطلبات')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرسوم')),
                ('processing_time', models.PositiveIntegerField(default=5, verbose_name='مدة المعالجة (أيام)')),
                ('icon', models.CharField(default='fas fa-building', max_length=50, verbose_name='أيقونة الخدمة')),
                ('color', models.CharField(default='#007bff', max_length=20, verbose_name='لون البطاقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='بوابة الخدمات الحكومية', max_length=100, verbose_name='اسم الموقع')),
                ('site_description', models.TextField(default='بوابة موحدة للخدمات الحكومية', verbose_name='وصف الموقع')),
                ('contact_email', models.EmailField(default='info@gov.ae', max_length=254, verbose_name='بريد التواصل')),
                ('contact_phone', models.CharField(default='+971-6-123-4567', max_length=20, verbose_name='هاتف التواصل')),
                ('address', models.TextField(default='الشارقة، دولة الإمارات العربية المتحدة', verbose_name='العنوان')),
                ('working_hours', models.CharField(default='الأحد - الخميس: 8:00 ص - 4:00 م', max_length=100, verbose_name='ساعات العمل')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الموظف')),
                ('role', models.CharField(choices=[('admin', 'الإدارة'), ('center', 'المركز')], max_length=20, verbose_name='الدور')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='القسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.center', verbose_name='المركز')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف موظف',
                'verbose_name_plural': 'ملفات الموظفين',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('status', 'استعلام عن حالة طلب'), ('general', 'استعلام عام'), ('complaint', 'شكوى'), ('suggestion', 'اقتراح')], max_length=20, verbose_name='نوع الاستعلام')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('request_reference', models.CharField(blank=True, max_length=50, verbose_name='رقم مرجعي للطلب')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('response', models.TextField(blank=True, verbose_name='الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رد بواسطة')),
            ],
            options={
                'verbose_name': 'استعلام',
                'verbose_name_plural': 'الاستعلامات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100, verbose_name='اسم مقدم الطلب')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('requester_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('requester_national_id', models.CharField(max_length=20, verbose_name='رقم الهوية')),
                ('request_details', models.TextField(verbose_name='تفاصيل الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('under_review', 'تحت المراجعة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('reserved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحجز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مُسند إلى')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.center', verbose_name='المركز')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_requests', to=settings.AUTH_USER_MODEL, verbose_name='محجوز بواسطة')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'طلب خدمة',
                'verbose_name_plural': 'طلبات الخدمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='services.servicerequest', verbose_name='الطلب')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة نصية',
                'verbose_name_plural': 'الرسائل النصية',
                'ordering': ['-sent_at'],
            },
        ),
    ]
