# Generated by Django 5.2.4 on 2025-10-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(max_length=254, verbose_name='البريد الإلكتروني / رقم الهاتف'),
        ),
    ]
