# Generated by Django 5.2.4 on 2025-10-14 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_inquiry_rejection_reason_inquiry_reserved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='ai_analysis_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات التحليل الذكي'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='case_type',
            field=models.CharField(choices=[('pending', 'قيد التحليل'), ('civil', 'مدني'), ('criminal', 'جزائي'), ('unknown', 'غير محدد')], default='pending', max_length=20, verbose_name='نوع القضية'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='case_type_confidence',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة الثقة بالتصنيف (%)'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='manual_classification',
            field=models.BooleanField(default=False, verbose_name='تصنيف يدوي'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='petition_text',
            field=models.TextField(blank=True, null=True, verbose_name='نص العريضة'),
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='الملف')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'صورة'), ('doc', 'مستند Word'), ('other', 'أخرى')], max_length=10, verbose_name='نوع الملف')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_size', models.IntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='النص المستخرج')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='services.servicerequest', verbose_name='البلاغ')),
            ],
            options={
                'verbose_name': 'ملف مرفق',
                'verbose_name_plural': 'الملفات المرفقة',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
