# Generated by Django 5.2.4 on 2025-10-17 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_servicerequest_ai_analysis_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المرجع')),
                ('complainant_name', models.CharField(max_length=200, verbose_name='اسم الشاكي')),
                ('complainant_id', models.CharField(max_length=50, verbose_name='رقم الهوية')),
                ('complainant_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('complainant_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('police_center', models.CharField(max_length=200, verbose_name='مركز الشرطة')),
                ('complaint_type', models.CharField(max_length=100, verbose_name='نوع البلاغ')),
                ('complaint_subject', models.TextField(blank=True, verbose_name='موضوع البلاغ')),
                ('incident_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الواقعة')),
                ('incident_time', models.TimeField(blank=True, null=True, verbose_name='وقت الواقعة')),
                ('incident_location', models.TextField(blank=True, verbose_name='مكان الواقعة')),
                ('incident_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('incident_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('relationship', models.CharField(blank=True, max_length=200, verbose_name='العلاقة بالمشكو ضده')),
                ('agreement_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الاتفاق')),
                ('money_seized', models.CharField(blank=True, max_length=10, verbose_name='استيلاء على مبلغ مالي')),
                ('seized_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المبلغ المستولى عليه')),
                ('seized_property', models.TextField(blank=True, verbose_name='الممتلكات المستولى عليها')),
                ('transfer_method', models.CharField(blank=True, max_length=100, verbose_name='طريقة التسليم')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المصرف')),
                ('account_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الحساب')),
                ('other_transfer_method', models.TextField(blank=True, verbose_name='طريقة تسليم أخرى')),
                ('has_witnesses', models.CharField(blank=True, max_length=10, verbose_name='وجود شهود')),
                ('witnesses_info', models.TextField(blank=True, verbose_name='بيانات الشهود')),
                ('has_evidence', models.CharField(blank=True, max_length=10, verbose_name='وجود إثباتات')),
                ('evidence_description', models.TextField(blank=True, verbose_name='وصف الإثباتات')),
                ('additional_statements', models.TextField(blank=True, verbose_name='أقوال إضافية')),
                ('accused_parties', models.JSONField(default=list, verbose_name='المشكو في حقهم')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('under_review', 'قيد المراجعة'), ('in_progress', 'قيد المعالجة'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], default='new', max_length=20, verbose_name='الحالة')),
                ('reserved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحجز')),
                ('staff_notes', models.TextField(blank=True, verbose_name='ملاحظات الموظف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name='محال إلى')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_reports', to=settings.AUTH_USER_MODEL, verbose_name='محجوز من قبل')),
            ],
            options={
                'verbose_name': 'بلاغ جنائي',
                'verbose_name_plural': 'البلاغات الجنائية',
                'ordering': ['-created_at'],
            },
        ),
    ]
