# Generated by Django 5.2.6 on 2025-11-11 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_reportnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50, verbose_name='رقم البلاغ')),
                ('report_year', models.IntegerField(verbose_name='السنة')),
                ('charge', models.CharField(max_length=500, verbose_name='التهمة')),
                ('bank_name', models.CharField(max_length=200, verbose_name='اسم البنك')),
                ('account_number', models.CharField(max_length=100, verbose_name='رقم الحساب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد المعالجة'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.center', verbose_name='مركز الاختصاص')),
            ],
            options={
                'verbose_name': 'طلب مخاطبة بنك',
                'verbose_name_plural': 'طلبات مخاطبة البنوك',
                'ordering': ['-created_at'],
            },
        ),
    ]
